'use strict';

// autogenerated - 4/29/2020

/*
 *
 * https://www.w3.org/Style/CSS/all-properties.en.html
 */

var implementedProperties = new Set();
implementedProperties.add("azimuth"); // Not implemented in NativeScript
implementedProperties.add("background");
implementedProperties.add("background-attachment"); // Not implemented in NativeScript
implementedProperties.add("background-color");
implementedProperties.add("background-image");
implementedProperties.add("background-position");
// Missing, but implemented in NativeScript as far as I can tell: background-size
implementedProperties.add("background-repeat");
implementedProperties.add("border");
implementedProperties.add("border-bottom");
implementedProperties.add("border-bottom-color");
implementedProperties.add("border-bottom-style"); // Not implemented in NativeScript
implementedProperties.add("border-bottom-width");
implementedProperties.add("border-collapse"); // Not implemented in NativeScript
implementedProperties.add("border-color");
implementedProperties.add("border-left");
implementedProperties.add("border-left-color");
implementedProperties.add("border-left-style"); // Not implemented in NativeScript
implementedProperties.add("border-left-width");
implementedProperties.add("border-right");
implementedProperties.add("border-right-color");
implementedProperties.add("border-right-style"); // Not implemented in NativeScript
implementedProperties.add("border-right-width");
implementedProperties.add("border-spacing"); // Not implemented in NativeScript
implementedProperties.add("border-style"); // Not implemented in NativeScript
implementedProperties.add("border-top");
implementedProperties.add("border-top-color");
implementedProperties.add("border-top-style");
implementedProperties.add("border-top-width");
implementedProperties.add("border-width");
implementedProperties.add("bottom"); // Not implemented in NativeScript
implementedProperties.add("clear"); // Not implemented in NativeScript
implementedProperties.add("clip"); // Not implemented in NativeScript
// Missing, but implemented in NativeScript as far as I can tell: clip-path
implementedProperties.add("color");
implementedProperties.add("css-float"); // Not implemented in NativeScript
implementedProperties.add("flex"); // NativeScript implements the longhand, but not this shorthand, though renderers may still want to.
implementedProperties.add("flex-basis");
implementedProperties.add("flex-grow");
implementedProperties.add("flex-shrink");
implementedProperties.add("float"); // Not implemented in NativeScript
implementedProperties.add("flood-color"); // Not implemented in NativeScript
implementedProperties.add("font");
implementedProperties.add("font-family");
implementedProperties.add("font-size");
implementedProperties.add("font-style");
implementedProperties.add("font-variant");
implementedProperties.add("font-weight");
implementedProperties.add("height");
implementedProperties.add("left");
implementedProperties.add("lighting-color"); // Not implemented in NativeScript
implementedProperties.add("line-height");
implementedProperties.add("margin");
implementedProperties.add("margin-bottom");
implementedProperties.add("margin-left");
implementedProperties.add("margin-right");
implementedProperties.add("margin-top");
implementedProperties.add("opacity");
implementedProperties.add("outline-color"); // Not implemented in NativeScript
implementedProperties.add("padding");
implementedProperties.add("padding-bottom");
implementedProperties.add("padding-left");
implementedProperties.add("padding-right");
implementedProperties.add("padding-top");
implementedProperties.add("right"); // Not implemented in NativeScript
implementedProperties.add("stop-color"); // Not implemented in NativeScript
implementedProperties.add("text-line-through-color"); // Not implemented in NativeScript
implementedProperties.add("text-overline-color"); // Not implemented in NativeScript
implementedProperties.add("text-underline-color"); // Not implemented in NativeScript
implementedProperties.add("top"); // Not implemented in NativeScript
implementedProperties.add("webkit-border-after-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-border-before-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-border-end-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-border-start-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-column-rule-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-match-nearest-mail-blockquote-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-tap-highlight-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-text-emphasis-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-text-fill-color"); // Not implemented in NativeScript
implementedProperties.add("webkit-text-stroke-color"); // Not implemented in NativeScript
implementedProperties.add("width");
module.exports = implementedProperties;
